/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Seccion;
import Clases.Curso;
import Clases.Docente;
import ListasEnlazadas.ListaSeccion;
import ListasEnlazadas.ListaCurso;
import ListasEnlazadas.NodoCurso;
import ListasEnlazadas.NodoDocente;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class frmNuevaSeccion extends javax.swing.JFrame {

    frmMenu menu;
    ListaCurso LC;
    ListaSeccion LS;
    frmInicioAdministrador IAdm;
    
    public frmNuevaSeccion(frmMenu menu,frmInicioAdministrador IAdm) {
        initComponents();
        this.menu=menu;
        LC=menu.LC;
        LS=menu.LS;
        this.IAdm=IAdm;
        
        llenarCbxCurso();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        txtCodigoAula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxDocente = new javax.swing.JComboBox<>();
        btnCrearSeccion = new javax.swing.JButton();
        btnVerSeccionesCreadas = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbLunes = new javax.swing.JCheckBox();
        jcbMartes = new javax.swing.JCheckBox();
        jcbMiercoles = new javax.swing.JCheckBox();
        jcbJueves = new javax.swing.JCheckBox();
        jcbViernes = new javax.swing.JCheckBox();
        jcbSabado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nuevas Secciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel2.setText("Código");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel3.setText("Curso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        cbxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 150, -1));

        txtCodigoAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 130, -1));

        jLabel4.setText("Docente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jPanel1.add(cbxDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 150, -1));

        btnCrearSeccion.setText("Crear seccion");
        btnCrearSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 110, -1));

        btnVerSeccionesCreadas.setText("Ver secciones creadas");
        btnVerSeccionesCreadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSeccionesCreadasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerSeccionesCreadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel5.setText("Dias");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jcbLunes.setText("Lunes");
        jPanel1.add(jcbLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jcbMartes.setText("Martes");
        jPanel1.add(jcbMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jcbMiercoles.setText("Miercoles");
        jPanel1.add(jcbMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jcbJueves.setText("Jueves");
        jPanel1.add(jcbJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        jcbViernes.setText("Viernes");
        jcbViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbViernesActionPerformed(evt);
            }
        });
        jPanel1.add(jcbViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));

        jcbSabado.setText("Sabado");
        jPanel1.add(jcbSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoActionPerformed
        // TODO add your handling code here:
      limpiarCbxDocente();
      llenarCbxDocente();
    }//GEN-LAST:event_cbxCursoActionPerformed

    private void btnCrearSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSeccionActionPerformed
        // TODO add your handling code here:
        String codigoAula=txtCodigoAula.getText();
        String nombreCurso=cbxCurso.getSelectedItem().toString();
        String docenteACargo=cbxDocente.getSelectedItem().toString();
        boolean lunes=jcbLunes.isSelected(),martes=jcbMartes.isSelected(),miercoles=jcbMiercoles.isSelected();
        boolean jueves=jcbJueves.isSelected(),viernes=jcbViernes.isSelected(),sabado=jcbSabado.isSelected();
        boolean[] diasC={lunes,martes,miercoles,jueves,viernes,sabado};
        String[] dias=new String[6];
        for(int i=0;i<6;i++){
            if(diasC[i]){
                dias[i]="Clase";
            }
        }
        
        
        NodoCurso auxNodoCurso=LC.getInicio();
        
        if(auxNodoCurso.buscarCurso(nombreCurso).getNombreCurso().equalsIgnoreCase(nombreCurso)){
            Curso auxCurso=auxNodoCurso.buscarCurso(nombreCurso);
            NodoDocente auxNodoDocente=auxCurso.getDocentesACargo().getInicio();
            if(auxNodoDocente.buscarDocente(docenteACargo).getNombre().equalsIgnoreCase(docenteACargo)){
                Docente auxDocente=auxNodoDocente.buscarDocente(docenteACargo);
                Seccion nuevaSeccion=new Seccion(codigoAula,auxCurso,auxDocente);
                nuevaSeccion.setMatrizHorario(dias);
                LS.insertarAlFinal(nuevaSeccion);
                
            }
        }

      
        
        
        
        
        
        
        
        
        /*
        Seccion aulaNueva=new Seccion(codigoAula,nombreCurso,docenteACargo);
        LS.insertarAlFinal(aulaNueva);*/
        
    }//GEN-LAST:event_btnCrearSeccionActionPerformed

    private void btnVerSeccionesCreadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSeccionesCreadasActionPerformed
        // TODO add your handling code here:
        frmVerSeccionesCreadas verSC=new frmVerSeccionesCreadas(menu,this);
        dispose();
        verSC.setVisible(true);
        
    }//GEN-LAST:event_btnVerSeccionesCreadasActionPerformed

    private void txtCodigoAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAulaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        dispose(); 
        IAdm.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jcbViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbViernesActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearSeccion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerSeccionesCreadas;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JComboBox<String> cbxDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbJueves;
    private javax.swing.JCheckBox jcbLunes;
    private javax.swing.JCheckBox jcbMartes;
    private javax.swing.JCheckBox jcbMiercoles;
    private javax.swing.JCheckBox jcbSabado;
    private javax.swing.JCheckBox jcbViernes;
    private javax.swing.JTextField txtCodigoAula;
    // End of variables declaration//GEN-END:variables

    private void llenarCbxCurso() {
        for(int i=0;i<LC.getSize();i++){
            
        cbxCurso.addItem(LC.getNodoByIndex(i).getDato().getNombreCurso());
        }
    }

    private void llenarCbxDocente() {
        String cursoCapturado=cbxCurso.getSelectedItem().toString();
        //Curso auxCurso=new Curso();
        for(int i=0;i<LC.getSize();i++){
            if(cursoCapturado.equalsIgnoreCase(LC.getNodoByIndex(i).getDato().getNombreCurso())){
                for(int j=0;j<LC.getNodoByIndex(i).getDato().getDocentesACargo().getSize();j++){
                    cbxDocente.addItem(LC.getNodoByIndex(i).getDato().getDocentesACargo().getNodoByIndex(j).getDato().getNombre());
                }
            }
        }
    }

    private void limpiarCbxDocente() {
        /*for(int i=cbxDocente.getItemCount();i>=1;i++){
            cbxDocente.removeItemAt(i-1);
        }*/
        cbxDocente.removeAllItems();
    }
    
    

   
}
